### ISSUE TITLE
news.jsonを生成する

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/covid19-gen-datajson-shizuokapref#10]
こちらのissueでnews.jsonの生成も必要になりそうなので、データ生成側で扱う

https://github.com/aktnk/covid19/issues/21

## 実装の内容

- スクレイピングで静岡県側のCOVID19関連の最新ニュースを取得
- エラーがある場合は生成せずに終了

## 懸念事項

- スクレイピングなのでサイトの構造が変わる場合は対処が必要
- 構造が変更される, サイトへのアクセスができない場合にエラー処理が必要

**Comment by hrsano645** [comment]
扱ってるブランチ: https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/tree/issue%2310-add_news_json

**Comment by aktnk** [comment]
https://github.com/aktnk/covid19/issues/21 にassign しましたので、お願いします。

**Comment by hrsano645** [comment]
新しいバージョンを作りました。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/05f6c2ffa205f1c5015e215927b295fef68096ea/gen_newsjson.py

生成の様子

![image](https://user-images.githubusercontent.com/23502/94332340-57a6f100-000f-11eb-8baa-98460dfbd7cc.png)

jsonの仕様で、同じ日付が二つあるとどちらか一つしか出せないですね😅

**Comment by hrsano645** [comment]
> jsonの仕様で、同じ日付が二つあるとどちらか一つしか出せないですね😅

これ間違いでした。ちゃんと出せます。タグのフィルターする正規表現が誤ってました。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/c00806cb2876eefe80aac88830cf22912ecc4897

![image](https://user-images.githubusercontent.com/23502/94332477-a99c4680-0010-11eb-96b1-2c71466067c9.png)

**Comment by aktnk** [comment]
日付けで探してくるのは、これまでのやり方より、ロバストですね！

**Comment by hrsano645** [comment]
@aktnk 日付の形は多分守られるはずです。急にきれいな構造に変わったらしょうがないですｗ

**Comment by hrsano645** [comment]
このissueを作った当初から現在までの経緯を少しあげると

- 富士市の対策サイトも作成 -> https://stopcovid19-fuji.netlify.app
- 富士市のニュース記事一覧をオープンデータ化されました -> https://opendata.pref.shizuoka.jp/dataset/8484.html
- 富士市側のニュース記事対応も視野に入れて、静岡県版も対応していきます
  - 富士市版はデータ生成はそれほど大変ではなさそう
  - 静岡県はスクレイピングをベースにしているので静岡県側のサイト構造が変わった時に修正が必要

**Comment by hrsano645** [comment]
静岡県側でスクレイピングに使っているライブラリを用意する必要があって、Pythonの仮想環境を作ってから実行する必要があります。初回と定期実行時の方法をまとめておくと

初回で行う仮想環境の作成方法
```
python -m venv .venv
pip install -r requirements.txt
```

定期実行時（静岡県版の実行例）bat.shを書き換えれば良さそう
```
# 仮想環境を有効化
source ./.venv/bin/activate

# bash bat.shの中身の実行
curl https://opendata.pref.shizuoka.jp/dataset/8167/resource/46009/220001_shizuoka_covid19_call_center.csv > call_center.csv
curl https://opendata.pref.shizuoka.jp/dataset/8167/resource/46279/220001_shizuoka_covid19_patients.csv > patients.csv
curl https://opendata.pref.shizuoka.jp/dataset/8167/resource/45876/220001_shizuoka_covid19_test_number.csv > test_number.csv
curl https://opendata.pref.shizuoka.jp/dataset/8167/resource/48851/220001_new_shizuoka_covid19_patients.csv > details_of_confirmed_cases.csv

# data.json生成
python patients.py patients.csv call_center.csv test_number.csv details_of_confirmed_cases.csv

# news.json生成
python gen_newsjson.py
```

あと考えないといけないこと

- 静岡県版と富士市版のnews.jsonをどうやって実行時に分けるか: patients.pyは地域名を引数指定することができるのでgen_news.jsonでもそうする
- 地域別にブランチを切って、gen_news.jsonを別々に実装して分けておく: 管理が面倒かも

**Comment by hrsano645** [comment]
gen_newsjson.pyは一つのファイルで提供して、富士市版と静岡版の両方対応をすることにしました。patients.pyと同様地域別フィルターと同じ方法で実装してみます。

**Comment by hrsano645** [comment]
news.json対応中のブランチはこちらです
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/tree/wip_news_json

**Comment by hrsano645** [comment]
ひとまず動くところまで作りました。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/tree/481ed8d0b25a678a99b102e85967304735ffc0f2

```
# 必要な環境がある状況でためします。
# 静岡県は引数無し
python gen_newsjson.py
# 富士市は引数あり
python gen_newsjson.py 富士市
```

まだやること

~- [ ] 地域フィルター周りが適当なのでもう少し煮詰めます~ -> 今のところ対応の必要性がないのでやめておきます。対応しない地域を入れると何も出力しないので
- [x] 静岡県の日付に西暦がないので西暦を付ける対応をする（年をまたぐ場合を考慮する）

**Comment by hrsano645** [comment]
後はPythonの仮想環境を作って、仮想環境上で実行する方法を用意しておけばよさそうです。シェルスクリプト素人なのでちょっと時間かかりそう。

参考: [venv環境でpythonスクリプトをcronで周期実行 - Qiita](https://qiita.com/gao_gao/items/12a1e9620bddbff7463f)

**Comment by hrsano645** [comment]
bat.shを改造して、Python仮想環境の有効と、仮想環境がない場合は作成を行うようにしてみました。crontabでの動作も確認済みです。

作業環境: Ubuntu 18.04

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/d38a142e50c6da6942557a179e7b3cec041bca39/bat.sh

bat.shの初めに`LOCALNAME`という変数を用意しました。こちらに地域名を入れると地域ごとのスクリプトの実行ができます。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/d38a142e50c6da6942557a179e7b3cec041bca39/bat.sh#L4

**Comment by aktnk** [comment]
dockerを使い、Windows pcでも開発やテストができるようにしたい！

**Comment by hrsano645** [comment]
@aktnk あー確かに。dockerfile追加してみましょうか。

**Comment by aktnk** [comment]
可能であればお願いします。

**Comment by hrsano645** [comment]
@aktnk すぐに作れなかったので、別のissueにさせてください。
