### ISSUE TITLE
PCR検査実施件数の新しいオープンデータフォーマットに対応する

### ISSUE THREAD

**Issue by hrsano645** [hrsano645/covid19-gen-datajson-shizuokapref#6]
#1, #5 で扱った後に、静岡県から連絡があった新しいデータフォーマットに対応する

注意点として

- 4/26までの検査実施件数累計が2行目にある, 1行目は列のヘッダー名
- 3行目(4/27）より日ごとの検査実施件数

現時点ではオープンデータの提供はまだ行われていないので、市川さん経由でいただいている仮のデータファイルを元に対応します。

**Comment by hrsano645** [comment]
data.jsonのデータ構造

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/issue-1_add_inspections_summary/data_format.md#inspection_persons-検査実施件数グラフを重ね合わせ

オープンデータ(.csv予定)の構造。変わる可能性あり
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/issue-1_add_inspections_summary/data_format.md#inspections_summarycsv予定

**Comment by hrsano645** [comment]
※Slackでも書きましたが、まとめと経緯を乗せておきます

まとめとして

- **data.jsonのmain_summaryにある、検査実施人数を検査実施件数に変更する予定でしたが、やめました**
- data.json内main_summaryにある「検査実施人数」の項目は、静岡県オープンデータのtest_peaple.csvから生成する状況をそのまま保持します
- 静岡県オープンデータのtest_people.csvが提供されなくなった場合の対応は、現時点では未定。検査実施件数に変更するのが第一候補と思ってます

以下まとめの詳細です

---

data.json内のmain_summary > 検査実施人数 を検査実施件数に変更する予定でしたが、対策サイト側の変更も必要になりそうです。

main_summaryの値が「検査陽性者の状況」カードのみに使われているものかはわかっていませんが、仮にその場合は影響範囲を調べる必要があって、すぐに対応するのは大変かなと思います。

現状、静岡県のオープンデータではtest_people.csvは提供されているので、提供が続く限りはそのままで良いのではと思ってます。

提供されない場合はまたその時に検討しなおす必要があります。検査実施件数に変更するのが第一候補と思ってます。

---
まとめの蛇足になりますが、、

このmain_summary > 検査実施人数は、対策サイト側でデータとして利用されていないかもしれません。

静岡県側の対策サイトの検査陽性者の状況カードを見ると、陽性者数（累計）から始まっていました。ここはdata.jsonのmain_summaryの内容を表示しているので、検査実施人数が出てこないのはおかしい気がしています。

https://stopcovid19.code4numazu.org/cards/details-of-confirmed-cases/

このカードを生成するコード上では、検査実施人数の項目は出さないようになっていました。メトロ版の現時点のdevelopment版でも出ていませんでした。

静岡県: https://github.com/aktnk/covid19/blob/development/components/ConfirmedCasesTable.vue
メトロ版: https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/ConfirmedCasesDetailsTable.vue

データの構造や受け取る側では検査実施人数の項目はあるので、もしかしたら過去に利用していたけど、利用しなくなった名残かもしれません。過去のlogを見ればわかりそうです。

**Comment by hrsano645** [comment]
現在までの進捗。データは生成できたので、対策サイト側でテストしてみます。

https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/898f5d6c4c03cc4ff6bc73b8c786e00584d314f8

**Comment by hrsano645** [comment]
自分の開発環境で データは https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/898f5d6c4c03cc4ff6bc73b8c786e00584d314f8 , @aktnk さんの検査実施件数の実装を使ってローカルで動かしてみたけど、よさそうです。

https://github.com/aktnk/covid19/tree/feature/aktnk%2317-add-inspections-graph

![image](https://user-images.githubusercontent.com/23502/85030202-215c0900-b1b8-11ea-8881-33a904beb72a.png)

**Comment by hrsano645** [comment]
いや良くなかったです... 正しいデータじゃなかったかも？

**Comment by aktnk** [comment]
対応ありがとうございます＆遅くまで、お疲れ様です。
いよいよ、準備が整ってきましたね。
もうひと踏ん張りです！

**Comment by hrsano645** [comment]
データは最新で、とりこめてるようですが、全部出ていなくて、なんでだろうって感じです。ちょっとまた見直してみます😅

**Comment by hrsano645** [comment]
@aktnk 
凡ミスでしたｗ data.jsonの置き場所を間違えていたので、おきなおしてみたら問題なかったようです。
![image](https://user-images.githubusercontent.com/23502/85033174-9f6ddf00-b1bb-11ea-8e1d-f186dc9812b3.png)

**Comment by aktnk** [comment]
すぐに解決して良かったです。
急いでいたりすると、ちょっとしたことでミスしたりしますので…

**Comment by hrsano645** [comment]
お騒がせしましたｗ 深夜にお酒飲んでやる作業じゃないですね😅

**Comment by aktnk** [comment]
判断鈍るかもしれませんね！

**Comment by hrsano645** [comment]
ブランチを変更しました -> 
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/tree/issue-6_update_inspections_summary

**Comment by hrsano645** [comment]
そろそろ移行できそうなのでPRだします～
